config/routes.rb
Rails.application.routes.draw do
  root to: "posts#home"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end
  resources :users, only: [:new, :show, :edit, :update]
  resources :posts, only: [:new, :index, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'tag_search'
    end
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post_comments
  
  def create
    @comment = Comment.create(comment_params)
  end
  
  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end

  def set_post_comments
    @post = Post.find(params[:post_id])
    @comments = @post.comments.includes(user: :profile)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% comments.each do |comment|%>
  <ul>
    <% if comment.user.profile.image.attached? %>
      <li><%= image_tag comment.user.profile.image, class: "liked_user_image" %></li>
    <% else %>
      <li><%= image_tag "default.png", class: "liked_user_image"%></li>
    <% end %>

    <li class="liked_user_nickname"><%= link_to comment.user.nickname, user_path(comment.user.id) %></li>
    <li class="comment"><%= safe_join(comment.text.split("\n"),tag(:br)) %></li>
    
    <% if current_user.id == comment.user.id %>
      <li><%= link_to "コメントを削除", post_comment_path(@post.id,comment.id), method: :delete, class: "comment_delete", remote: true %>
    <% end %>
  </ul>
<% end %>

app/views/comments/create.js.erb
$("#add_comment").html("<%= j(render("comments/comment", comments: @comments)) %>");
$("#comment_content").val("");

app/views/comments/destroy.js.erb
$("#add_comment").html("<%= j(render("comments/comment", comments: @comments)) %>");
$("#comment_content").val("");