config/routes.rb
Rails.application.routes.draw do
  root to: "posts#home"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end
  resources :users, only: [:new, :show, :edit, :update]
  resources :posts, only: [:new, :index, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'tag_search'
    end
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/equipment.rb
class Equipment < ActiveHash::Base
  self.data = [
    { id: 1, name: '身体一つ！' },
    { id: 2, name: 'ダンベル' },
    { id: 3, name: 'ダンベル+インクラインベンチ' },
    { id: 4, name: 'ヨガマット' },
    { id: 5, name: 'ジムマシン'},
    { id: 6, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/experience.rb
class Experience < ActiveHash::Base
  self.data = [
    { id: 1, name: '1ヶ月未満' },
    { id: 2, name: '1〜3ヶ月' },
    { id: 3, name: '半年程度' },
    { id: 4, name: '1年以上' },
    { id: 5, name: '2年以上' },
    { id: 6, name: '5年以上' },
    { id: 7, name: '10年以上' },
    { id: 8, name: '20年以上' }
  ]

  include ActiveHash::Associations
  has_many :profiles
end

app/models/frequency.rb
class Frequency < ActiveHash::Base
  self.data = [
    { id: 1, name: '週1~2回' },
    { id: 2, name: '週3' },
    { id: 3, name: '週4~5' },
    { id: 4, name: '週6以上' },
  ]

  include ActiveHash::Associations
  has_many :profiles
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/part.rb
class Part < ActiveHash::Base
  self.data = [
    { id: 1, name: '大胸筋' },
    { id: 2, name: '広背筋・僧帽筋' },
    { id: 3, name: '肩・三角筋' },
    { id: 4, name: '上腕二頭筋' },
    { id: 5, name: '上腕三頭筋' },
    { id: 6, name: '腹筋' },
    { id: 7, name: '尻・大臀筋' },
    { id: 8, name: '脚・大腿四頭筋' }
  ]

  include ActiveHash::Associations
  has_many :profiles
  has_many :posts
end

app/models/place.rb
class Place < ActiveHash::Base
  self.data = [
    { id: 1, name: '自宅' },
    { id: 2, name: 'ジム' },
    { id: 3, name: '屋外' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments,dependent: :destroy
  has_many :likes,dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :part
  belongs_to :equipment
  belongs_to :place

  with_options presence: true do
    validates :text,          length: { maximum: 210 }
    validates :part_id,       numericality: { only_integer: true, message: "が未選択になっています"}
    validates :equipment_id,  numericality: { only_integer: true, message: "が未選択になっています"}
    validates :place_id,      numericality: { only_integer: true, message: "が未選択になっています"}
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :image

  with_options presence: true do
    validates :experience_id, numericality: { only_integer: true, message: "が未選択になっています"}
    validates :part_id, numericality: { only_integer: true, message: "が未選択になっています"  }
    validates :frequency_id,  numericality: { only_integer: true, message: "が未選択になっています" }
    validates :introduction,  length: { maximum: 100 }
  end
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :frequency
  belongs_to :part
  belongs_to :experience
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  has_one :profile, dependent: :destroy
  has_many :sns_credentials
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  validates :nickname, presence: true, length: { maximum: 15 }
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,}+\z/i.freeze, message: '半角英数字を含める必要があります' }

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email)
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :home
  before_action :set_post, only: [:show, :destroy]
  before_action :search_post, only: [:home, :search]

  def home
  end

  def search
    @results = @p.result.includes(:comments,:likes, :liked_users,user: :profile).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      flash[:post_notice] = "投稿が完了しました！"
      redirect_to controller: :users, action: :show, id: @post.user_id
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(user: :profile)
  end

  def destroy
    redirect_to root_path and return unless current_user.id == @post.user_id
    if @post.destroy
      flash[:post_notice] = "投稿を削除しました！"
      redirect_to controller: :users, action: :show, id: @post.user_id
    else
      render :show
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:text, :part_id, :equipment_id, :place_id, :start_time).merge(user_id: current_user.id)
  end

  def search_post
    @p = Post.ransack(params[:q])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: :new
  before_action :authenticate_user!, only: [:show, :edit, :update]
  
  def new
  end

  def show
    @posts = @user.posts.includes(:comments, :likes, :liked_users).order(created_at: :desc)
    @array = part_count
  end

  def edit
    redirect_to action: :show,id: @user.id and return unless current_user.id == @user.id
    @profile = @user.profile
  end

  def update
    @profile = @user.profile
    @profile.update(user_params)
    if @profile.valid?
      redirect_to action: :show
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:profile).permit(:experience_id, :part_id, :frequency_id, :introduction, :image)
  end

  def part_count
    array = []
    @posts.each do |post|
      part_id = post.part_id
      array << part_id
    end
    array
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareTraining</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error_alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class="error_message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="main_header">
  <div class="left_header">
    <div class="app_title">
      <%= link_to "ShareTraining", root_path, class: "app_logo" %>
    </div>
    <% if user_signed_in? %>
      <div class="current_user_name">
        こんにちは！<%= current_user.nickname%>さん
      </div>
    <% end %>
  </div>
  <div class="notice_message">
    <%= flash[:post_notice] %>
  </div>
  <div class="right_header">
    <div class="sign_in_box">
      <% if user_signed_in? %>
        <%= link_to "マイページ", user_path(current_user.id), class: "header_btn"%>
        <%= link_to "Shareする", new_post_path, class: "header_btn"%>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header_btn"%>
      <% else %>
        <%= link_to "新規登録", new_user_path, class: "header_btn" %>
        <%= link_to "ログイン", new_user_session_path, class: "header_btn"%>
      <% end %>
    </div>
  </div>
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '◁先月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '来月▷'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>