config/routes.rb
Rails.application.routes.draw do
  root to: "posts#home"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end
  resources :users, only: [:new, :show, :edit, :update]
  resources :posts, only: [:new, :index, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'tag_search'
    end
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments,dependent: :destroy
  has_many :likes,dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :part
  belongs_to :equipment
  belongs_to :place

  with_options presence: true do
    validates :text,          length: { maximum: 210 }
    validates :part_id,       numericality: { only_integer: true, message: "が未選択になっています"}
    validates :equipment_id,  numericality: { only_integer: true, message: "が未選択になっています"}
    validates :place_id,      numericality: { only_integer: true, message: "が未選択になっています"}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :home
  before_action :set_post, only: [:show, :destroy]
  before_action :search_post, only: [:home, :search]

  def home
  end

  def search
    @results = @p.result.includes(:comments,:likes, :liked_users,user: :profile).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      flash[:post_notice] = "投稿が完了しました！"
      redirect_to controller: :users, action: :show, id: @post.user_id
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(user: :profile)
  end

  def destroy
    redirect_to root_path and return unless current_user.id == @post.user_id
    if @post.destroy
      flash[:post_notice] = "投稿を削除しました！"
      redirect_to controller: :users, action: :show, id: @post.user_id
    else
      render :show
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:text, :part_id, :equipment_id, :place_id, :start_time).merge(user_id: current_user.id)
  end

  def search_post
    @p = Post.ransack(params[:q])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like_list.html.erb
<h2 class="liked_user_title">NiceTrainingしたユーザー</h2>
<% post.liked_users.each do |user| %>
  <ul>
    <% if user.profile.image.attached? %>
      <li><%= image_tag user.profile.image, class: "liked_user_image" %></li>
    <% else %>
      <li><%= image_tag "default.png", class: "liked_user_image"%></li>
    <% end %>
    <li class="liked_user_nickname"><%= link_to user.nickname, user_path(user.id) %></li>
  </ul>
<% end %>

app/views/posts/_posts.html.erb
<div class="index_wrapper">
  <div class="shared_posts_wrapper">
    <div class="shared_post">
      <div class="user_wrapper">
        <div class="user_info">
          <div class="user_icon">
            <% if post.user.profile.image.attached?%>
              <%= image_tag post.user.profile.image, class: "post_user_image" %>
            <% else %>
              <%= image_tag "default.png", class: "post_user_image"%>
            <% end %>
          </div>
          <div class="user_name">
            <%= link_to post.user.nickname, user_path(post.user_id) %>
          </div>
        </div>
        <div class="user_introduction">
          <%= safe_join(post.user.profile.introduction.split("\n"),tag(:br)) %>
        </div>
      </div>
      <div class="post_text_wrapper">
        <% unless current_page?(post_path(post.id)) && (current_user.id != post.user_id) %>
          <div class="more">
            <span><%= image_tag 'arrow.png' %></span>
            <ul class="more_lists_wrapper">
              <% unless current_page?(post_path(post.id)) %>
                <li class="more_lists">
                  <%= link_to "詳細", post_path(post.id), class: "show_btn" %>
                </li>
              <% end %>
              <% if current_user.id == post.user_id%>
                <li class="more_lists">
                  <%= link_to "削除", post_path(post.id), method: :delete, class: "show_btn", data: { confirm: '本当に削除しますか？' }  %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="shared_text">
          <%= safe_join(post.text.split("\n"),tag(:br)) %>
        </div>
        <div class="tag_list_field">
          <ul>
            <li>実施日：<%= l post.created_at %></li>
            <li>部位：<%= post.part.name %></li>
            <li>器具：<%= post.equipment.name %></li>
            <li>場所：<%= post.place.name %></li>
          </ul>
          <div class="muscle_count", id="post_like_<%= post.id %>" >
            <%= render "likes/like", { post: post } %>           
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_search.html.erb
<div class="search_form" id="is_fixed">
  <%= search_form_for @p, url: search_posts_path do |f| %>
    <%= f.search_field :text_cont, placeholder: "キーワード", class: "search_text_field"%>
    <%= f.collection_select :part_id_eq, Part.all, :id, :name, {include_blank: '部位'}, {class: "tag_search_form"} %>
    <%= f.collection_select :equipment_id_eq, Equipment.all, :id, :name, {include_blank: '器具'}, {class: "tag_search_form"}%>
    <%= f.collection_select :place_id_eq, Place.all, :id, :name, {include_blank: 'トレーニング場所'}, {class: "tag_search_form"}%>
    <%= f.submit '検索', class: "search_btn"%>
  <% end %>
</div>

app/views/posts/home.html.erb
<%= render "shared/header"%>
<div class="" id="home">
  <div class="home_title" id="title">
  </div>
  <%= render "search" %>
</div>
<div class="home_part">
  <div class="part_title">
    部位から探す
  </div>
  <div class= "parts_wrapper">
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :part_id_eq, Part.all, :id, :name, {selected: "1"}, {class: "hidden"} %>
        <%= f.submit "大胸筋", class: "part_btn chest cover"%>
      <% end %>
    </div>
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :part_id_eq, Part.all, :id, :name, {selected: "2"}, {class: "hidden"} %>
        <%= f.submit "広背筋・僧帽筋", class: "part_btn back cover"%>
      <% end %>
    </div>
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :part_id_eq, Part.all, :id, :name, {selected: "3"}, {class: "hidden"} %>
        <%= f.submit "肩・三角筋", class: "part_btn shoulder cover"%>
      <% end %>
    </div>
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :part_id_eq, Part.all, :id, :name, {selected: "4"}, {class: "hidden"} %>
        <%= f.submit "上腕二頭筋", class: "part_btn arm2 cover"%>
      <% end %>
    </div>
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :part_id_eq, Part.all, :id, :name, {selected: "5"}, {class: "hidden"} %>
        <%= f.submit "上腕三頭筋", class: "part_btn arm3 cover"%>
      <% end %>
    </div>
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :part_id_eq, Part.all, :id, :name, {selected: "6"}, {class: "hidden"} %>
        <%= f.submit "腹筋", class: "part_btn abs cover"%>
      <% end %>
    </div>
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :part_id_eq, Part.all, :id, :name, {selected: "7"}, {class: "hidden"} %>
        <%= f.submit "尻・大臀筋", class: "part_btn hip cover"%>
      <% end %>
    </div>
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :part_id_eq, Part.all, :id, :name, {selected: "8"}, {class: "hidden"} %>
        <%= f.submit "脚・大腿四頭筋", class: "part_btn leg cover"%>
      <% end %>
    </div>
  </div>
  <div class="part_title">
    器具から探す
  </div>
  <div class= "parts_wrapper">
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :equipment_id_eq, Equipment.all, :id, :name, {selected: "1"}, {class: "hidden"} %>
        <%= f.submit "身体一つ!", class: "part_btn only_body cover"%>
      <% end %>
    </div>
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :equipment_id_eq, Equipment.all, :id, :name, {selected: "2"}, {class: "hidden"} %>
        <%= f.submit "ダンベル", class: "part_btn dumbbell cover"%>
      <% end %>
    </div>
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :equipment_id_eq, Equipment.all, :id, :name, {selected: "4"}, {class: "hidden"} %>
        <%= f.submit "ダンベル＋ベンチ", class: "part_btn dum_bench cover"%>
      <% end %>
    </div>
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :equipment_id_eq, Equipment.all, :id, :name, {selected: "5"}, {class: "hidden"} %>
        <%= f.submit "ヨガマット", class: "part_btn yoga cover"%>
      <% end %>
    </div>
    <div class="part_item">
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.collection_select :equipment_id_eq, Equipment.all, :id, :name, {selected: "6"}, {class: "hidden"} %>
        <%= f.submit "ジムマシン", class: "part_btn gim_machine cover"%>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render "shared/header"%>

<%= form_with model: @post, url:  posts_path, local: true do |f|%>

  <div class="post_field">
    <div class="post_wrapper">
      <%= render "shared/error_messages", model: f.object %>
      <div class="post_input_area">
        <div class="post_text">
          <%= f.text_area :text,class: "text_area", id: "text_area_id", placeholder: "トレーンングメニューをシェアしよう!!"%>
          <div class="text_count", id="text_counting">0文字</div>
        </div>
        <div class="tag_field">
          <div class="tag_form">
            <%= f.collection_select(:part_id, Part.all, :id, :name, {include_blank: '部位を選択'}, {class: "tag_decoration"}) %>
          </div>
          <div class="tag_form">
            <%= f.collection_select(:equipment_id, Equipment.all, :id, :name, {include_blank: '器具を選択'}, {class: "tag_decoration"}) %>
          </div>
          <div class="tag_form">
            <%= f.collection_select(:place_id, Place.all, :id, :name, {include_blank: '場所を選択'}, {class: "tag_decoration"}) %>
          </div>
        </div>
        <div class="post_btn">
          <%= f.submit "投稿する", class: "submit_btn"%>
        </div>
      </div>
      <div class="hidden">
        <%= f.datetime_select :start_time ,{default: Date.today} %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/search.html.erb
<%= render "shared/header"%>
<div class="serch_container">
  <%= render "search"%>
</div>

<div class="searched_posts_title">
</div>

 <% if @results.empty? %>
  <div class="no_data">
    検索結果がありません
  </div>
  <div class="top_page_link">
    <%= link_to "トップページへ戻る", root_path %>
  </div>
 <% end%>

<%= render partial: "posts", collection: @results, as: "post" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class="post_show_title">
  <%= link_to "#{@post.user.nickname}さんの投稿詳細", user_path(@post.user_id) %>
</div>

<%= render "posts", { post: @post } %>
<div class="like_comennt_wrapper">
  <div class="liked_user_wrapper", id="liked_list_id">
    <%= render "like_list", { post: @post } %>
  </div>
  <div class="comments_wrapper">
    <h2 class="comments_form_title">コメントする</h2>
    <div class="comennts_form">
      <%= form_with model: [@post, @comment], url: post_comments_path(@post.id) do |f|%>
        <%= f.text_area :text,id: "comment_content", placeholder: "例）１セットの回数はどうやって決めていますか？", rows: "3" , class: "comment_area"%>
        <%= f.submit "投稿する", class: "comment_btn", id: "comment_submit" %>
      <% end %>
    </div>
    <h2 class="comments_list_title">コメント一覧</h2>
    <div class="comments_list", id="add_comment">
      <%= render "comments/comment" , { comments: @comments } %>
    </div>
  </div>
</div>